services:
  - type: web
    name: phishguard-flask
    env: python
    buildCommand: "pip install torch==2.6.0 && pip install -r requirements.txt --no-deps"
    startCommand: "python phishing_analyzer.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
